TargonCChat:
  
  Config:
  
    # Enviar mensagens no chat ?
    # true / false
    useChatMsg: true
    
    # Enviar mensagens na ActionBar ?
    # true / false
    useActionBar: true
  
    # De quanto em quanto tempo o chat irá limpar automaticamente ?
    # Em SEGUNDOS!
    tempoTotal: 600
    
    # O aviso será dado em quanto tempo ?
    # Em SEGUNDOS!
    tempoAviso: 10
    
  Mensagens:
  
    # Mensagem de aviso quando o tempo atingir o "tempoAviso" acima.
    iraLimparAutomatico:
      - '&7* O Chat será limpo daqui a &6{tempo} &7segundos!'
      - '&7* Plugin by &6JaoBalalao&7.'
    
    # Mensagem de aviso quando o tempo zerar e o chat for limpo.
    chatLimpoAutomatico:
      - '&7* O Chat foi limpo automaticamente!'
      - '&7* Plugin by &6JaoBalalao&7.'
      
    # Mensagem que aparecerá ao digitar o comando /clearchat.
    iraLimparAdmin:
      - '&7* O Administrador &6{admin} &7agendou uma limpeza de chat.'
      - '&7* O Chat será limpo daqui a &6{tempo} &7segundos!'
      - '&7* Plugin by &6JaoBalalao&7.'
      
    # Mensagem que aparecerá ao limpar o chat pelo comando /clearchat.
    chatLimpoAdmin:
      - '&7* O Chat foi limpo por &6{admin}&7!'
      - '&7* Plugin by &6JaoBalalao&7.'
      
    # Mensagem na ActionBAR de aviso quando o tempo atingir o "tempoAviso" acima.
    iraLimparAutomatico_ActionBar: '&7* O Chat será limpo daqui a &6{tempo} &7segundos!'
    
    # Mensagem na ActionBAR  de aviso quando o tempo zerar e o chat for limpo.
    chatLimpoAutomatico_ActionBar: '&7* O Chat foi limpo automaticamente!'
      
    # Mensagem na ActionBAR  que aparecerá ao digitar o comando /clearchat.
    iraLimparAdmin_ActionBar: '&7* O Administrador &6{admin} &7agendou uma limpeza de chat. &6({tempo}s)'
      
    # Mensagem na ActionBAR  que aparecerá ao limpar o chat pelo comando /clearchat.
    chatLimpoAdmin_ActionBar: '&7* O Chat foi limpo por &6{admin}&7!'
