TargonCChat:
  
  Config:
  
    # De quanto em quanto tempo o chat irá limpar automaticamente ?
    # Em SEGUNDOS!
    tempoTotal: 600
    
    # O aviso será dado em quanto tempo ?
    # Em SEGUNDOS!
    tempoAviso: 10
    
  Mensagens:
  
    # Mensagem de aviso quando o tempo atingir o "tempoAviso" acima.
    iraLimparAutomatico:
      - '&7* O Chat será limpo daqui a &6{tempo} &7segundos!'
      - '&7* Plugin by &6JaoBalalao&7.'
    
    # Mensagem de aviso quando o tempo zerar e o chat for limpo.
    chatLimpoAutomatico:
      - '&7* O Chat foi limpo automaticamente!'
      - '&7* Plugin by &6JaoBalalao&7.'
      
    # Mensagem que aparecerá ao digitar o comando /clearchat.
    iraLimparAdmin:
      - '&7* O Administrador &6{admin} &7agendou uma limpeza de chat.'
      - '&7* O Chat será limpo daqui a &6{tempo} &7segundos!'
      - '&7* Plugin by &6JaoBalalao&7.'
      
    # Mensagem que aparecerá ao limpar o chat pelo comando /clearchat.
    chatLimpoAdmin:
      - '&7* O Chat foi limpo por &6{admin}&7!'
      - '&7* Plugin by &6JaoBalalao&7.'